### ISSUE TITLE
USA.gov data is no longer available

### ISSUE THREAD

**Issue by hdavies5608** [jdorfman/awesome-json-datasets#125]
As seen [here](https://github.com/usagov/1.USA.gov-Data) the service has been deactivated and as such all the URLs are no longer valid. Is the data available elsewhere or should it be removed?

**Comment by benhastings** [comment]
The short version is this:
They decommissioned the url shortening agreement with bit.ly, but it appears that either:

1. They have chosen to cease delivering any of the non-authenticated content in JSON format
2. They have broken the webserver handling of the url requests.

Based on what I see, it's the former, not the latter.  Too, the investigation lead me to data.gov, and there is a mountain of data there... but one must secure a developer API key to get at the content programmatically.

I've read through each of the pages referenced here: https://www.usa.gov/developer#item-211492 and following the instructions they've included for the non-shortened URLs all lead to 404s

I'm not sure how to spin this, but I did some research and crawling but would love to get hacktoberfest credit if at all possible!  Perhaps I could update the readme.md for the usa.gov content?

**Comment by DraftYeti5608** [comment]
Good find, thank you for looking into it. However the data should be available without authentication to be put on the list, you could submit a pull request to remove the URLs that don't work anymore.

cc: @jdorfman

**Comment by hdavies5608** [comment]
Fixed as of PR #142
