### ISSUE TITLE
Feature Request: Size

### ISSUE THREAD

**Issue by codekiln** [jdorfman/awesome-json-datasets#180]
I was looking for a quick json file to use in a codepen. It wasn't clear which of these were rather large (50MB+) and which were small enough to use for a small example (< 1 MB). It would be helpful to have a couple datasets that are small so as to facilitate prototyping.

**Comment by jdorfman** [comment]
@codekiln Good call! I will leave this open and when I have some time I will explore ways this can get done while abiding by Awesome™ rules.

**Comment by jdorfman** [comment]
now, now Mr. Bot. We are still working on this.

**Comment by Mandihamza** [comment]
Hey @codekiln!  I wanted to run a couple of options by you.

1.  We could simply append a notation at the end of the title like this:
      **Science Fiction Novels (10MB)**
2. We could use an emoji to indicate the size:
![image](https://user-images.githubusercontent.com/23363171/34448214-97bf7708-eca8-11e7-847d-773b1793e12d.png)

Let me know what you think!

**Comment by codekiln** [comment]
Great idea!

**Comment by Mandihamza** [comment]
Great!  I can see benefits to both options.  Stating the size explicitly makes the datasets easy to scan, while using emojis may help simplify the sizes into categories like; <10MB, <20MB, <30MB etc.

@jdorfman, I'm curious which option you think will work best?

**Comment by jdorfman** [comment]
@MandihamzaI think we should pick 3 size categories to adhere to the [manifesto's](https://github.com/sindresorhus/awesome/blob/master/awesome.md) theme "You should rather leave stuff out than include too much.".

I'm thinking `<1MB`, `<5MB`, `>10MB`
Emoji options: ?

Actually, just come up with a few real examples and we'll vote on it from there. Create a [gist](https://gist.github.com/) and share your ideas here.

**Comment by jdorfman** [comment]
@Mandihamza your call
