### ISSUE TITLE
Some links don't work anymore

### ISSUE THREAD

**Issue by doubleOrt** [jdorfman/awesome-json-datasets#182]
The Historical Events links to https://vizgr.com are not working. And the Open Movie Database links require API keys now.

**Comment by jdorfman** [comment]
Good catch. Want to make a PR? If not I will do it.

**Comment by doubleOrt** [comment]
@jdorfman  Well, I have no idea how to fix those, I was just testing each of the APIs out and some links didn't work.

**Comment by jdorfman** [comment]
@doubleOrt got ya. I will get this done asap. Thanks!

**Comment by jdorfman** [comment]
If you need a PR for Hacktoberfest 2017, it's yours. Just claim it first by leaving a comment so someone doesn't work on the same issue. ;)

**Comment by tophernuts** [comment]
I'll remove any links that don't work!

**Comment by tophernuts** [comment]
Also all of those https://vizgr.com/ links seem to work
