### ISSUE TITLE
FYI: Strong types for these datasets

### ISSUE THREAD

**Issue by dvdsgl** [jdorfman/awesome-json-datasets#185]
Please check out https://github.com/typeguard/awesome-typed-datasets

I've started using [quicktype](https://github.com/quicktype/quicktype) to generate strongly-typed code in Go, C++, Objective-C, Java, TypeScript, Swift, Elm, and C# for reading and writing the JSON data from these APIs. I'll submit a PR to your main README with a link once the project matures a bit.

**Comment by dvdsgl** [comment]
One thing I'm doing is [specifying these datasets as JSON data themselves](https://github.com/typeguard/awesome-typed-datasets/tree/master/datasets). It would probably be a good idea to make this awesome list of JSON datasets a JSON dataset, rather than only a Markdown list. A normalized JSON dataset with metadata and endpoints for all of the listed datasets would be awesome and so meta! 😆

**Comment by jdorfman** [comment]
Sounds good. Make sure the endpoint is JSON =)

Closing this for now.
