### ISSUE TITLE
Make awesome-json-datasets an awesome JSON dataset

### ISSUE THREAD

**Issue by dvdsgl** [jdorfman/awesome-json-datasets#186]
One thing I'm doing for #185 is specifying these datasets as a JSON dataset. It would be a good idea to make this awesome list of JSON datasets an awesome JSON dataset itself, rather than just a Markdown list.

A normalized JSON dataset with metadata and endpoints for all of the listed datasets would be even more awesome and so meta! 😆

**Comment by jdorfman** [comment]
This is actually a great idea. I like how recursive it is. How would you automate it? A [probot](https://github.com/probot/probot) that creates a PR with the JSON would be ideal.

**Comment by dvdsgl** [comment]
The simplest approach would be to have a single `data.json` at the top-level that contains the data for each dataset, then simple shell script or python program that generates your `README.md`.

**Comment by jdorfman** [comment]
@dvdsgl I'm not opposed. Shell would be ideal since it is easier for most to get started (plus a great excuse to use [SHML](http://shml.xyz))

Let me think about it. My main concern is alienating folks that just want to make a quick edit to the markdown file.
