### ISSUE TITLE
Add Star Wars API

### ISSUE THREAD

**Issue by arnaudvalle** [jdorfman/awesome-json-datasets#200]
see https://swapi.co/documentation

**Comment by jdorfman** [comment]
I think that would be a great addition. Even it's own category after "Reddit"

![image](https://user-images.githubusercontent.com/398230/46982073-b9bef380-d08f-11e8-9218-efbec32f05e8.png)

List the following endpoints:

- films
- people
- planets
- species
- starships
-  vehicles
