### ISSUE TITLE
Add more datasets during Hacktoberfest

### ISSUE THREAD

**Issue by jdorfman** [jdorfman/awesome-json-datasets#21]
Welcome Hacktoberfest-ers! 

If you know of any `JSON` datasets and need more Pull Requests for the limited edition GitHub/@DigitalOcean t-shirt then look no further. If you don't know of any `JSON` datasets, all good, you can find many using your favorite search engine or just look through the current list and find missing/broken endpoints.

**ProTips:**
📖  Make sure to read the [contributing guidelines](https://github.com/jdorfman/awesome-json-datasets/blob/master/CONTRIBUTING.md)
🐦  Tell your friends about this issue on [Twitter](https://twitter.com/intent/tweet?url=https%3A%2F%2Fgithub.com%2Fjdorfman%2Fawesome-json-datasets%2Fissues%2F21&via=jdorfman&text=I%27m%20adding%20more%20Awesome%20JSON%20datasets%20on%20@GitHub%20for%20%23Hacktoberfest)
ℹ️  Learn more about Hacktoberfest here: https://hacktoberfest.digitalocean.com

**Comment by unluisco** [comment]
I would to collab

**Comment by machikoyasuda** [comment]
What is JSON? I read about it here: https://en.wikipedia.org/wiki/JSON#Example :)

**Comment by hemangsk** [comment]
Hey everyone! 😄 
Added Github Meta JSON in PR #33

**Comment by jdorfman** [comment]
Nice we got featured in the last Hacktoberfest newsletter!: 
![image](https://cloud.githubusercontent.com/assets/398230/19320983/682c038c-9068-11e6-8283-c290fbb8d271.png)

Great job everyone. =)

**Comment by jschiarizzi** [comment]
Just saw you in the news letter and thought I would add what I thought of.  Just submitted pull request for a movie section.  

Great list everyone!

**Comment by jdorfman** [comment]
Hockey stick star growth since Hacktoberfest

![image](https://cloud.githubusercontent.com/assets/398230/19414289/8b4b9f94-92fc-11e6-8cf6-5fd533cc13dc.png)

**Comment by matty22** [comment]
What about different versions of games? For example, there are a hundred different versions of Monopoly. Should those be submitted or not?

**Comment by kipply** [comment]
https://github.com/jdorfman/awesome-json-datasets/pull/156

**Comment by jdorfman** [comment]
Huge thanks to all that participated in this years Hacktoberfest! I will be merging the open PRs ASAP so don't think I am just ignoring yours 😉  

Have a great Halloween! 🎃 👻
