### ISSUE TITLE
Population.io links don't work anymore

### ISSUE THREAD

**Issue by FOSSforlife** [jdorfman/awesome-json-datasets#212]
It looks like [their API](https://population.io/) now requires a signup.

Some potential alternatives, based on a Google search:
- https://www.census.gov/data/developers/data-sets/popest-popproj/popest.html
- https://www.worldpop.org/sdi/introapi
- https://datausa.io/about/api/

**Comment by jdorfman** [comment]
@FOSSforlife BUMMER! Thanks for reporting. Want to put in a pull request? If not I'll just remove it.

**Comment by FOSSforlife** [comment]
I found some other broken links as well so I'll do a PR in a min :)
