### ISSUE TITLE
Add SpaceX

### ISSUE THREAD

**Issue by jdorfman** [jdorfman/awesome-json-datasets#214]
https://docs.spacexdata.com/?version=latest

**Comment by kipariz** [comment]
Hello! What exactly help is needed?

**Comment by jdorfman** [comment]
Hi @kipariz I was thinking of renaming `[NASA](https://github.com/jdorfman/awesome-json-datasets#nasa)` to `Space` and adding the following endpoints:

* https://api.spacexdata.com/v3/launches
* https://api.spacexdata.com/v3/missions
* https://api.spacexdata.com/v3/history 

Thoughts?

**Comment by kipariz** [comment]
@jdorfman 
I don't know is it helpful, but maybe something like this (if I understand you correctly).

### Space

-  other links
 - SpaceX
   -  Launches
   -  Missions
   -  History

**Comment by jdorfman** [comment]
@kipariz love it!
