### ISSUE TITLE
Add Sports section

### ISSUE THREAD

**Issue by jdorfman** [jdorfman/awesome-json-datasets#64]
Start with NFL
- [NFL](http://www.nfl.com/liveupdate/scorestrip/ss.json)

Put in other: https://github.com/BurntSushi/nflgame/tree/master/nflgame/gamecenter-json

**Comment by dcmoore** [comment]
Ok, so I did some sleuthing on the 'ole interwebs and came up with how the NFL feeds their game center with that sweet sweet JSON data.

Take the following URL: http://www.nfl.com/liveupdate/game-center/2016092500/2016092500_gtd.json

You get lots of information! However it isn't immediately apparent how that number in the URL is derived. If you put in the incorrect number, then you'll get a 404. The number format is as such:
```
id  2016092500
year      2016
month       09
day         25
game number 00
```

The game number starts at zero and increments to the number of games that were played on that date.

NFL data mystery solved! :shipit:

**Comment by jdorfman** [comment]
Stellar work @dcmoore
