### ISSUE TITLE
Weather now requires api key?

### ISSUE THREAD

**Issue by ethanpil** [jdorfman/awesome-json-datasets#9]
Looks like the weather isn't working without a key.

**Comment by jdorfman** [comment]
@ethanpil lame. Will check for alternatives. Thanks for reporting.

**Comment by jdorfman** [comment]
Looks like the Yahoo Developer Network has a good public dataset: https://developer.yahoo.com/weather/

Before I start, @ethanpil want to create a PR?

**Comment by ethanpil** [comment]
Nah, go ahead and do your thing! :)

**Comment by jdorfman** [comment]
@ethanpil come on lets take "17 contributions in the last year" to `18`! I'll even throw in a free MaxCDN shirt: https://twitter.com/jdorfman/status/736204805836705792

**Comment by ethanpil** [comment]
No need for the shirt. Happy to contribute, save it for someone who has to do a lot of work.
